Areas/Tour/Controllers/EndLocationsAdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HKQTravellingAuthenication.Areas.Tour.Extension;
using HKQTravellingAuthenication.Data;
using HKQTravellingAuthenication.Models.Tour;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HKQTravellingAuthenication.Areas.Tour.Controllers
{
	[Area("Tour")]
	[Route("end-location-manager")]
	[Authorize(Roles = RoleName.Administrator + "," + RoleName.Editor)]
	public class EndLocationsAdministratorController : Controller
	{
		private readonly ApplicationDbContext _context;

		public EndLocationsAdministratorController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Admin/EndLocationsAdministrator
		[HttpGet]
		[Route("index")]
		public async Task<IActionResult> Index()
		{
			return _context.endLocations != null ?
						View(await _context.endLocations.ToListAsync()) :
						Problem("Entity set 'ApplicationDBContext.endLocations'  is null.");
		}

		// GET: Admin/EndLocationsAdministrator/Create
		[HttpGet]
		[Route("create")]
		public IActionResult Create()
		{
			return View();
		}

		// POST: Admin/EndLocationsAdministrator/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[Route("create")]
		public async Task<IActionResult> Create(IFormCollection formColection)
		{
			string endLocation = formColection["EndLocationName"].ToString();
			if (endLocation == null)
			{
				ViewData["validation_message"] = "Điểm đến không được để trống!";
				return View();
			}
			else if (checkingEndLocation.checkEndLocationName(_context, endLocation))
			{
				ViewData["validation_message"] = "Điểm đến đã tồn tại!";
				return View();
			}
			else
			{
				var dbEndLocation = new EndLocations()
				{
					EndLocationName = endLocation,
				};
				_context.Add(dbEndLocation);
				await _context.SaveChangesAsync();
				return RedirectToAction("Index");
			}
		}

		// GET: Admin/EndLocationsAdministrator/Edit/5
		[HttpGet]
		[Route("edit/{id}")]
		public async Task<IActionResult> Edit(long? id)
		{
			if (id == null || _context.endLocations == null)
			{
				return NotFound();
			}

			var endLocations = await _context.endLocations.FindAsync(id);
			if (endLocations == null)
			{
				return NotFound();
			}
			return View(endLocations);
		}

		// POST: Admin/EndLocationsAdministrator/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[Route("edit/{id}")]
		public async Task<IActionResult> Edit(long id, IFormCollection formCollection)
		{
			string endLocation = formCollection["EndLocationName"].ToString();
			var dbEndLocation = await _context.endLocations.FindAsync(id);
			try
			{
				if (endLocation == null)
				{
					ViewData["validation_message"] = "Điểm đến không được để trống!";
					return View();
				}
				else if (checkingEndLocation.checkEndLocationNameWhenUpdate(_context, endLocation))
				{
					ViewData["validation_message"] = "Điểm đến đã tồn tại!";
					return View();
				}
				else
				{
					dbEndLocation.EndLocationName = endLocation;
					_context.Update(dbEndLocation);
					await _context.SaveChangesAsync();
					return RedirectToAction("Index");
				}
			}
			catch (DbUpdateConcurrencyException)
			{
				//Điều hướng đến trang lỗi
				return View();
			}
		}

		// GET: Admin/EndLocationsAdministrator/Delete/5
		[HttpGet]
		[Route("delete/{id}")]
		public async Task<IActionResult> Delete(long? id)
		{
			if (id == null || _context.endLocations == null)
			{
				return NotFound();
			}

			var endLocations = await _context.endLocations
				.FirstOrDefaultAsync(m => m.EndLocationId == id);
			if (endLocations == null)
			{
				return NotFound();
			}

			return View(endLocations);
		}

		// POST: Admin/EndLocationsAdministrator/Delete/5
		[HttpPost]
		[Route("delete/{id}")]
		public async Task<IActionResult> DeleteConfirmed(long id)
		{
			if (_context.endLocations == null)
			{
				return Problem("Entity set 'ApplicationDBContext.endLocations'  is null.");
			}
			var endLocations = await _context.endLocations.FindAsync(id);
			if (endLocations != null)
			{
				var toursToUpdate = await _context.tours.Where(t => t.TourId == id).ToListAsync();
				foreach (var tour in toursToUpdate)
				{
					tour.EndLocationId = null;
				}
				_context.endLocations.Remove(endLocations);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool EndLocationsExists(long id)
		{
			return (_context.endLocations?.Any(e => e.EndLocationId == id)).GetValueOrDefault();
		}
	}
}

Areas/Tour/Views/EndLocationsAdministrator/Create.cshtml
@model HKQTravellingAuthenication.Models.Tour.EndLocations

@{
    ViewData["Title"] = "Tạo mới điểm đến";
    Layout = "_Layout";
}
<div class="tile">
    <h3 class="tile-tile">Tạo mới thông tin điểm khởi hành</h3>
    <form asp-action="Create" asp-controller="EndLocationsAdministrator" asp-area="Tour" method="post">
        <div class="tile-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label" for="EndLocationName">Tên điểm kết thúc</label>
                    <input class="form-control" type="text" id="EndLocationName" name="EndLocationName" />
                    <p class="text-danger">@ViewData["validation_message"]</p>
                </div>
            </div>
        </div>
        <button class="btn btn-save" value="Create" type="submit">Lưu lại</button>
        <a class="btn btn-cancel" href="@Url.Action("Index", "EndLocationsAdministrator", new { area = "Tour" })">Hủy bỏ</a>
    </form>
</div>

Areas/Tour/Views/EndLocationsAdministrator/Delete.cshtml
@model HKQTravellingAuthenication.Models.Tour.EndLocations

@{
    ViewData["Title"] = "Xóa bỏ điểm đến";
    Layout = "_Layout";
}
<style>
    .dl-horizontal {
        display: flex;
        flex-wrap: wrap;
    }

        .dl-horizontal dt {
            flex-basis: 30%; /* Điều chỉnh độ rộng của các phần tử dt */
            flex-shrink: 0;
            margin-right: 15px; /* Khoảng cách giữa các phần tử dt và dd */
        }

        .dl-horizontal dd {
            flex-basis: 70%; /* Điều chỉnh độ rộng của các phần tử dd */
            flex-shrink: 0;
        }
</style>

<div>
    <h3 class="tile-tile">Bạn có chắc chắn là xóa điểm kết thúc này?</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EndLocationName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndLocationName)
        </dd>
    </dl>

    <form asp-action="Delete" asp-controller="EndLocationsAdministrator" asp-area="Tour" method="post">
        <input type="hidden" asp-for="EndLocationId" />
        <button class="btn btn-save" value="Delete" type="submit">Xóa</button>
        <a class="btn btn-cancel" href="@Url.Action("Index", "EndLocationsAdministrator", new { area = "Tour" })">Hủy bỏ</a>
    </form>
</div>

Areas/Tour/Views/EndLocationsAdministrator/Edit.cshtml
@model HKQTravellingAuthenication.Models.Tour.EndLocations

@{
    ViewData["Title"] = "Cập nhật điểm đến";
    Layout = "_Layout";
}
<div class="tile">
    <h3 class="tile-tile">Cập nhật điểm kết thúc</h3>
    <form asp-action="Edit" asp-controller="EndLocationsAdministrator" asp-area="Tour" method="post">
        <div class="tile-body">
            <div class="row">
                <input type="hidden" asp-for="EndLocationId" />
                <div class="form-group col-md-6">
                    <label class="control-label" for="EndLocationName">Tên điểm kết thúc</label>
                    <input asp-for="EndLocationName" class="form-control" name="EndLocationName" value="@Model.EndLocationName" />
                    <p class="text-danger">@ViewData["validation_message"]</p>
                </div>
            </div>
        </div>

        <button class="btn btn-save" value="Save" type="submit">Lưu lại</button>
        <a class="btn btn-cancel" href="@Url.Action("Index", "EndLocationsAdministrator", new { area = "Tour" })">Hủy bỏ</a>
    </form>
</div>

Areas/Tour/Views/EndLocationsAdministrator/Index.cshtml
@model IEnumerable<HKQTravellingAuthenication.Models.Tour.EndLocations>

@{
    ViewData["Title"] = "Quản lý điểm đến";
    Layout = "_Layout";
}

@* @section Breadcrumb {
    @{
        ViewData["BreadcrumbTitle"] = "Index for end location";
    }
} *@

<div class="tile">
    <h3 class="tile-tile">Quản lý điểm kết thúc</h3>

    <p>
        <a href="@Url.Action("Create", "EndLocationsAdministrator", new { area = "Tour" })">Create New</a>
    </p>

    <table class="table" id="endLocationsTable">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index">@Html.DisplayNameFor(model => model.EndLocationId)</a>
                </th>
                <th>
                    <a asp-action="Index">@Html.DisplayNameFor(model => model.EndLocationName)</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndLocationId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndLocationName)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "EndLocationsAdministrator", new { area = "Tour", id = item.EndLocationId })">Edit</a> |
                        <a href="@Url.Action("Delete", "EndLocationsAdministrator", new { area = "Tour", id = item.EndLocationId })">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#endLocationsTable').DataTable({
                // Tùy chọn DataTables có thể thêm ở đây
            });
        });
    </script>
}