Areas/Tour/Controllers/StartLocationsAdministratorController.cs
using HKQTravellingAuthenication.Areas.Tour.Extension;
using HKQTravellingAuthenication.Data;
using HKQTravellingAuthenication.Models.Tour;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HKQTravellingAuthenication.Areas.Tour.Controllers
{
    [Area("Tour")]
    [Route("start-location-manager")]
    [Authorize(Roles = RoleName.Administrator + "," + RoleName.Editor)]
    public class StartLocationsAdministratorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StartLocationsAdministratorController(ApplicationDbContext context)
        {
            _context = context;
        }

        #region CRUD Start Location Administrator
        // GET: Admin/StartLocationsAdministrator
        [HttpGet]
        [Route("index")]
        public async Task<IActionResult> Index(string sortedOrder)
        {
            return _context.startLocations != null ?
                        View(await _context.startLocations.ToListAsync()) :
                        Problem("Entity set 'ApplicationDBContext.startLocations'  is null.");
        }

        // GET: Admin/StartLocationsAdministrator/Create
        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/StartLocationsAdministrator/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        [Route("create")]
        public async Task<IActionResult> Create(IFormCollection formColection)
        {
            string startLocation = formColection["StartLocationName"].ToString();
            if (startLocation == null)
            {
                ViewData["validation_message"] = "Điểm khởi hành không được để trống!";
                return View();
            }
            else if (checkingStartLocation.checkStartLocationName(_context, startLocation))
            {
                ViewData["validation_message"] = "Điểm khởi hành đã tồn tại!";
                return View();
            }
            else
            {
                var dbStartLocation = new StartLocations()
                {
                    StartLocationName = startLocation,
                };
                _context.Add(dbStartLocation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
        }

        // GET: Admin/StartLocationsAdministrator/Edit/5
        [HttpGet]
        [Route("edit/{id}")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.startLocations == null)
            {
                return NotFound();
            }

            var startLocations = await _context.startLocations.FindAsync(id);
            if (startLocations == null)
            {
                return NotFound();
            }
            return View(startLocations);
        }

        // POST: Admin/StartLocationsAdministrator/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("edit/{id}")]
        public async Task<IActionResult> Edit(long id, IFormCollection formCollection)
        {
            string startLocation = formCollection["StartLocationName"].ToString();
            var dbStartLocation = await _context.startLocations.FindAsync(id);
            try
            {
                if (startLocation == null)
                {
                    ViewData["validation_message"] = "Điểm khởi hành không được để trống!";
                    return View();
                }
                else if (checkingStartLocation.checkStartLocationNameWhenUpdate(_context, startLocation))
                {
                    ViewData["validation_message"] = "Điểm khởi hành đã tồn tại!";
                    return View();
                }
                else
                {
                    dbStartLocation.StartLocationName = startLocation;
                    _context.Update(dbStartLocation);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                //Điều hướng đến trang lỗi
                return View();
            }
        }

        // GET: Admin/StartLocationsAdministrator/Delete/5
        [HttpGet]
        [Route("delete/{id}")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.startLocations == null)
            {
                return NotFound();
            }

            var startLocations = await _context.startLocations
                .FirstOrDefaultAsync(m => m.StartLocationId == id);
            if (startLocations == null)
            {
                return NotFound();
            }

            return View(startLocations);
        }

        // POST: Admin/StartLocationsAdministrator/Delete/5
        [HttpPost]
        [Route("delete/{id}")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.startLocations == null)
            {
                return Problem("Entity set 'ApplicationDBContext.startLocations'  is null.");
            }
            var startLocations = await _context.startLocations.FindAsync(id);
            if (startLocations != null)
            {
                var toursToUpdate = await _context.tours.Where(t => t.TourId == id).ToListAsync();
                foreach(var tour in toursToUpdate)
                {
                    tour.StartLocationId = null;
                }
                _context.startLocations.Remove(startLocations);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StartLocationsExists(long id)
        {
            return (_context.startLocations?.Any(e => e.StartLocationId == id)).GetValueOrDefault();
        }
        #endregion
    }
}

Areas/Tour/Views/StartLocationsAdministrator/Create.cshtml
@model HKQTravellingAuthenication.Models.Tour.StartLocations

@{
    ViewData["Title"] = "Tạo mới điểm đi";
    Layout = "_Layout";
}
@* @section Breadcrumb {
    @{
        ViewData["BreadcrumbTitle"] = "Create for start location";
    }
} *@
<div class="tile">
    <h3 class="tile-tile">Tạo mới thông tin điểm khởi hành</h3>
    <form asp-action="Create" asp-controller="StartLocationsAdministrator" asp-area="Tour" method="post">
        <div class="tile-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label" for="StartLocationName">Tên điểm khởi hành</label>
                    <input class="form-control" type="text" id="StartLocationName" name="StartLocationName" />
                    <p class="text-danger">@ViewData["validation_message"]</p>
                </div>
            </div>
        </div>
        <button class="btn btn-save" value="Create" type="submit">Lưu lại</button>
        <a class="btn btn-cancel" href="@Url.Action("Index", "StartLocationsAdministrator", new { area = "Tour" })">Hủy bỏ</a>
    </form>
</div>

Areas/Tour/Views/StartLocationsAdministrator/Delete.cshtml
@model HKQTravellingAuthenication.Models.Tour.StartLocations

@{
    ViewData["Title"] = "Loại bỏ điểm đi";
    Layout = "_Layout";
}
<style>
    .dl-horizontal {
        display: flex;
        flex-wrap: wrap;
    }

        .dl-horizontal dt {
            flex-basis: 30%; /* Điều chỉnh độ rộng của các phần tử dt */
            flex-shrink: 0;
            margin-right: 15px; /* Khoảng cách giữa các phần tử dt và dd */
        }

        .dl-horizontal dd {
            flex-basis: 70%; /* Điều chỉnh độ rộng của các phần tử dd */
            flex-shrink: 0;
        }
</style>

<div class="tile">
    <h3 class="tile-tile">Bạn có chắc chắn là xóa điểm khởi hành này?</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartLocationName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartLocationName)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-controller="StartLocationsAdministrator" asp-area="Tour" method="post">
        <input type="hidden" asp-for="StartLocationId" />
        <button class="btn btn-save" value="Delete" type="submit">Xóa</button>
        <a class="btn btn-cancel" href="@Url.Action("Index", "StartLocationsAdministrator", new { area = "Tour" })">Hủy bỏ</a>
    </form>
</div>

Areas/Tour/Views/StartLocationsAdministrator/Edit.cshtml
@model HKQTravellingAuthenication.Models.Tour.StartLocations

@{
    ViewData["Title"] = "Cập nhật điểm đi";
    Layout = "_Layout";
}

<div class="tile">
    <h3 class="tile-tile">Cập nhật điểm khởi hành</h3>
    <form asp-action="Edit" asp-controller="StartLocationsAdministrator" asp-area="Tour" method="post">
        <div class="tile-body">
            <div class="row">
                <input type="hidden" asp-for="StartLocationId" />
                <div class="form-group col-md-6">
                    <label class="control-label" for="StartLocationName">Tên điểm khởi hành</label>
                    <input asp-for="StartLocationName" class="form-control" name="StartLocationName" value="@Model.StartLocationName" />
                    <p class="text-danger">@ViewData["validation_message"]</p>
                </div>
            </div>
        </div>

        <button class="btn btn-save" value="Save" type="submit">Lưu lại</button>
        <a class="btn btn-cancel" href="@Url.Action("Index", "StartLocationsAdministrator", new { area = "Tour" })">Hủy bỏ</a>
    </form>
</div>

Areas/Tour/Views/StartLocationsAdministrator/Index.cshtml
@model IEnumerable<HKQTravellingAuthenication.Models.Tour.StartLocations>

@{
    ViewData["Title"] = "Quản lý điểm đi";
    Layout = "_Layout";
}

<div class="tile">
    <h3 class="tile-tile">Quản lý điểm khởi hành</h3>
    <p>
        <a href="@Url.Action("Create", "StartLocationsAdministrator", new { area = "Tour" })">Create New</a>
    </p>
    <table class="table" id="startLocationsTable">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index">@Html.DisplayNameFor(model => model.StartLocationId)</a>
                    @* @Html.DisplayNameFor(model => model.StartLocationId) *@
                </th>
                <th>
                    <a asp-action="Index">@Html.DisplayNameFor(model => model.StartLocationName)</a>
                    @* @Html.DisplayNameFor(model => model.StartLocationName) *@
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartLocationId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartLocationName)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "StartLocationsAdministrator", new { area = "Tour", id = item.StartLocationId })">Edit</a> |
                        <a href="@Url.Action("Delete", "StartLocationsAdministrator", new { area = "Tour", id = item.StartLocationId })">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#startLocationsTable').DataTable({
                // Tùy chọn DataTables có thể thêm ở đây
            });
        });
    </script>
}